from __future__ import annotations

from pathlib import Path

ACTIVATE_TEMPLATE = """# Auto-generated by ctags-indexing-mcp. source this once per shell:
#   source {activate_path}
#
# After sourcing, any `vim` invocation auto-attaches:
#   - tags : {tags_path}
#   - cscope DB : {cscope_path}
# Works from any cwd. Detects whether `vim` resolves to neovim and uses
# cscope_maps.nvim's :Cs command, falling back to vim's :cs.

if [[ -n ${{BASH_SOURCE[0]:-}} ]]; then
    _ci_self="${{BASH_SOURCE[0]}}"
elif [[ -n ${{ZSH_VERSION:-}} ]]; then
    _ci_self="${{(%):-%x}}"
else
    _ci_self="$0"
fi
export CODEINDEX_DIR="$(cd "$(dirname "$_ci_self")" && pwd)"
export CODEINDEX_PROJECT="{project_root}"
unset _ci_self

if [[ ! -f "$CODEINDEX_DIR/cscope.out" || ! -f "$CODEINDEX_DIR/tags" ]]; then
    echo "ctags-indexing: artifacts missing in $CODEINDEX_DIR -- run index_regen via MCP or {regen_hint}" >&2
fi

export CSCOPE_DB="$CODEINDEX_DIR/cscope.out"

_ci_vim_is_nvim() {{
    if alias vim >/dev/null 2>&1; then
        local a
        a="$(alias vim 2>/dev/null)"
        [[ $a == *nvim* ]] && return 0
    fi
    local target
    target="$(command -v vim 2>/dev/null || true)"
    [[ -n $target ]] && readlink -f "$target" 2>/dev/null | grep -q nvim && return 0
    return 1
}}

if _ci_vim_is_nvim; then
    _ci_vim_mode=nvim
    vim() {{
        command nvim \\
            --cmd "set tags+=$CODEINDEX_DIR/tags" \\
            -c "silent! Cs db add $CODEINDEX_DIR/cscope.out" \\
            "$@"
    }}
else
    _ci_vim_mode=vim
    vim() {{
        command vim \\
            --cmd "set tags+=$CODEINDEX_DIR/tags" \\
            -c "silent! cs add $CODEINDEX_DIR/cscope.out" \\
            "$@"
    }}
fi
unset -f _ci_vim_is_nvim

echo "ctags-indexing: project=$CODEINDEX_PROJECT, vim wrapper installed ($_ci_vim_mode mode)"
unset _ci_vim_mode
"""


def generate_activate_script(
    output_dir: Path,
    project_root: Path,
    regen_hint: str = "rerun the index_create tool",
) -> Path:
    output_dir = output_dir.resolve()
    project_root = project_root.resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    activate_path = output_dir / "activate.sh"
    body = ACTIVATE_TEMPLATE.format(
        activate_path=activate_path,
        tags_path=output_dir / "tags",
        cscope_path=output_dir / "cscope.out",
        project_root=project_root,
        regen_hint=regen_hint,
    )
    activate_path.write_text(body)
    activate_path.chmod(0o644)
    return activate_path
